### ISSUE TITLE
Καλησπέρα!! Για το 1ο βήμα έκανα οτι γράφετε αλλά μου εμφανίζει αυτο

### ISSUE THREAD

**Issue by AggelosXrn** [merkourisa/Advanced-Interaction-Tecnologies-Applications-Individual-Assignment#7]
Καλησπέρα!! Για το 1ο βήμα έκανα οτι γράφετε αλλά μου εμφανίζει αυτο 
![image](https://user-images.githubusercontent.com/101424559/197344945-a1d2c51a-4168-445b-9cb6-12e7fe971252.png)
Προσπάθησα και κατέβασα το gstreamer , διάβασα και αυτό https://gstreamer.freedesktop.org/documentation/installing/on-windows.html?gi-language=c έκανα οτι λέει αλλά μου εμφανίζει ακριβώς το ίδιο error, το βίντεο library for processing 3 μου έχει κατέβει κανονικά.

_Originally posted by @EvitaXen in https://github.com/merkourisa/Advanced-Interaction-Tecnologies-Applications-Individual-Assignment/issues/1#issuecomment-1287812884_
     Καλησπέρα έχω το ίδιο θέμα μήπως το έχουμε λύσει τελικά?

**Comment by merkourisa** [comment]
@AggelosXrn καλησπέρα, καλό θα ήταν να μην ανοίγετε νέα isssues για τυχόν απορίες και να ποσταρέτε τις ερωτήσεις μέσα στα αντίστοιχα issues. Δες τι πρότεινα στην EvitaXen και αν δεν παίξει μπορούμε να το δούμε μαζί αύριο το βράδυ μέσω τηλεσυνάντησης  ή από κοντά στο εργαστήριο την Πέμπτη
